# Generated by Django 5.0.7 on 2024-07-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_alter_traveldetails_drop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetails',
            name='drop',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='pickup',
            field=models.CharField(max_length=200),
        ),
    ]
